# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf820cdf544c9ea329573a8b0b26e7545a8997b0fcc2c0a6e602f023b99eb8712c613d2db2bea463bbe4cf5457c1995e870968116953d8f3f574597157ce5583

test:
  secret_key_base: afa1c9b8c714f8c5002feea7ccb42ba82083a3a2087313c2cb67ca464184afa674d3d756f72ad35f986624f9ef9d064d44c73d4c4ffe99cc5e5c58001c3a1c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
